const employeesData = [
  {
    id: 1,
    firstName: "Marie",
    lastName: "Dupont",
    position: "Développeuse Front-End",
    service: "Informatique",
    email: "marie.dupont@entreprise.com",
    entryDate: "2021-08-12",
    status: "Actif",
  },
  {
    id: 2,
    firstName: "Paul",
    lastName: "Martin",
    position: "Comptable",
    service: "Ressources Humaines",
    email: "paul.martin@entreprise.com",
    entryDate: "2020-01-05",
    status: "Actif",
  },
  {
    id: 3,
    firstName: "Sophie",
    lastName: "Bernard",
    position: "Chargée RH",
    service: "Ressources Humaines",
    email: "sophie.bernard@entreprise.com",
    entryDate: "2019-03-18",
    status: "Actif",
  },
  {
    id: 4,
    firstName: "Thomas",
    lastName: "Leroy",
    position: "Technicien Support",
    service: "Informatique",
    email: "thomas.leroy@entreprise.com",
    entryDate: "2022-11-10",
    status: "Actif",
  },
  {
    id: 5,
    firstName: "Claire",
    lastName: "Moreau",
    position: "Responsable Communication",
    service: "Marketing",
    email: "claire.moreau@entreprise.com",
    entryDate: "2018-06-22",
    status: "Actif",
  },
  {
    id: 6,
    firstName: "Hugo",
    lastName: "Renaud",
    position: "Chef de Projet",
    service: "Informatique",
    email: "hugo.renaud@entreprise.com",
    entryDate: "2023-02-01",
    status: "Actif",
  },
  {
    id: 7,
    firstName: "Julie",
    lastName: "Fabre",
    position: "Assistante Administrative",
    service: "Ressources Humaines",
    email: "julie.fabre@entreprise.com",
    entryDate: "2017-09-14",
    status: "Actif",
  },
  {
    id: 8,
    firstName: "Adrien",
    lastName: "Colin",
    position: "UX Designer",
    service: "Design",
    email: "adrien.colin@entreprise.com",
    entryDate: "2022-04-08",
    status: "Actif",
  },
  {
    id: 9,
    firstName: "Lucie",
    lastName: "Petit",
    position: "Responsable Marketing",
    service: "Marketing",
    email: "lucie.petit@entreprise.com",
    entryDate: "2016-12-01",
    status: "Actif",
  },
  {
    id: 10,
    firstName: "Nicolas",
    lastName: "Girard",
    position: "Data Analyst",
    service: "Informatique",
    email: "nicolas.girard@entreprise.com",
    entryDate: "2020-07-19",
    status: "Inactif",
  },
];

export default employeesData;
